identityserver:
    build: .
    dockerfile: docker-identityserver.dockerfile
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

api:
    build: .
    dockerfile: docker-api.dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MVCAndAPISample_IdentityServer__Authority=http://localhost:5000
    ports:
      - "5001:5001"
    links:
      - identityserver:localhost

client:
    build: .
    dockerfile: docker-client.dockerfile
    container_name: client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MVCAndAPISample_IdentityServer__Authority=http://localhost:5000
      - MVCAndAPISample_Api__BaseAddress=http://api:5001
    ports:
      - "5002:5002"
    links:
      - identityserver:localhost
      - api